### ISSUE TITLE
Incorrect value for the hosts blocked

### ISSUE THREAD

**Issue by crazyontech** [decoderman/AB-Solution#6]
I have the latest version of AB-Solution installed on my RT-AC68U.

Number of hosts blocked in top of the launcher shows an incorrect value. You can replicate this by doing the following.

Say for example there were 500 ads blocked by ab-solution, 
1. When i first launch into ab-solution it shows 500 (which is correct)
2. Take option ls to see the current log status in the terminal
3. Go back to the main installer screen.
4. Now check the Number of hosts blocked. It shows 1000
5. Following the steps 2-4 again increases the value to 1500

Let me know if i am doing something wrong.

**Comment by decoderman** [comment]
This is not a live counter, it is updated when the scheduled hosts update runs, when you run the hosts update manually [u], when weekly [ws] or current stats [ls] is run.
I hope that helps understanding it.

**Comment by crazyontech** [comment]
Can you make it to refresh the counter whenever the AB-Solution installer is launched or refreshed. This will give a more up to date info. Also, when i use option [ls], i just see the top 10 ad domains blocked. Is there a way to list all the ad domains blocked(not just the top 10)..If you want to move these questions to the forum, please let me know.

**Comment by decoderman** [comment]
Yes please, I practically live in that forum. It's where things are happening. GitHub is a stale thing for me.
A selected few are currently testing the next version, AB-Solution 2.1. 
I have a feature freeze for this coming version, otherwise it will never see the light of day. 
I have considered your auto refresher some time ago and decided not to do it.
The counting is not the problem but the file handling afterwards to make sure it does not count the counted ones again. It's a heavy burden on the little router. And starting AB-Solution triggers already a complete system check in v2.1.

**Comment by decoderman** [comment]
Good news: Your comment got my brain working in the background.
I now have a much better way of counting ads.
It will be implemented in v2.1.
Thanks for contributing...
