### ISSUE TITLE
Suggestion: Updating stats

### ISSUE THREAD

**Issue by protik77** [decoderman/AB-Solution#9]
Hi,

I started using Ab-Solution recently in my `AC-68U` and it's a fantastic piece of code. I have to work with bash occasionally and I know how much hair pulling it takes to make something work with bash. I really appreciate what you are doing.

So after I started using Ab-Solution, it has become a habit of looking at the stats on the homepage every now and then. When the UI starts or I use `ac` to update the stats, 1. there is a spike in the CPU usage and 2. it takes a while to update the stats. I assume that is because to update the stats the code is going through the whole log file.

So to update the stats faster and make it easy on CPU usage, one thing can be done is to append the stat to the log file when it is updated. When updating stats next time, the code can start from the last log entry.

Let me know if that makes sense.

**Comment by decoderman** [comment]
Your idea makes sense and is exactly how it's done in the run_ads_counter() functions:
First I look if the marker "ab-solution-ads-counter" is found in the dnsmasq.log file.
If not, it counts the complete file.
If the marker "ab-solution-ads-counter" is found, it only counts from there, deletes the old marker and sets a new one at the end of the file.

Since the dnsmasq.log file can be large, it may take a while to count the relevant occurrences.
This is the spike you see, along with a soft restart of Dnsmasq (kill -USR2 $(pidof dnsmasq)).
This is also the reason why the logfiles are rotated daily at 5:20 in the morning, to lower the size of the dnsmasq.log file in use and make the counting faster when starting the AB-Solution UI and when running ac.

BTW, the subsequent calculation of the total, weekly and new values only takes a fraction of a moment.

**Comment by protik77** [comment]
I see. That's awesome! Thanks for the response.
